In [122]:
import numpy as np
import pandas as pd 
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,recall_score,classification_report,confusion_matrix

In [123]:
df=pd.read_csv(r"F:\BosscoderExcel\penguins_lter.csv",encoding_errors='ignore')

In [124]:
df1=df.copy()
df1.sample(2)

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
298,PAL0809,79,Gentoo penguin (Pygoscelis papua),Anvers,Biscoe,"Adult, 1 Egg Stage",N60A1,Yes,11/9/08,45.2,13.8,215.0,4750.0,FEMALE,8.24694,-26.65359,NaN
81,PAL0809,82,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N39A2,Yes,11/2/08,42.9,17.6,196.0,4700.0,MALE,8.63259,-26.23027,NaN

In [125]:
df1.ndim

2

In [126]:
df1.shape

(344, 17)

In [127]:
df1.size

5848

In [128]:
df1.sample(2)

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
177,PAL0708,26,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N89A2,No,11/28/07,52.0,19.0,197.0,4150.0,MALE,9.36799,-24.47142,NaN
77,PAL0809,78,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N37A2,Yes,11/6/08,37.2,19.4,184.0,3900.0,MALE,8.35540,-26.44787,NaN

In [129]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   studyName            344 non-null    object
 1   Sample Number        344 non-null    int64
 2   Species              344 non-null    object
 3   Region               344 non-null    object
 4   Island               344 non-null    object
 5   Stage                344 non-null    object
 6   Individual ID        344 non-null    object
 7   Clutch Completion    344 non-null    object
 8   Date Egg             344 non-null    object
 9   Culmen Length (mm)   342 non-null    float64
 10  Culmen Depth (mm)    342 non-null    float64
 11  Flipper Length (mm)  342 non-null    float64
 12  Body Mass (g)        342 non-null    float64
 13  Sex                  334 non-null    object
 14  Delta 15 N (o/oo)    330 non-null    float64
 15  Delta 13 C (o/oo)    331 non-null    float64
 16  Comments             26 non-null     object
dtypes: float64(6), int64(1), object(10)
memory usage: 45.8+ KB

In [130]:
df1.isna().sum()

studyName                0
Sample Number            0
Species                  0
Region                   0
Island                   0
Stage                    0
Individual ID            0
Clutch Completion        0
Date Egg                 0
Culmen Length (mm)       2
Culmen Depth (mm)        2
Flipper Length (mm)      2
Body Mass (g)            2
Sex                     10
Delta 15 N (o/oo)       14
Delta 13 C (o/oo)       13
Comments               318
dtype: int64

In [131]:
df1.isnull().sum()

studyName                0
Sample Number            0
Species                  0
Region                   0
Island                   0
Stage                    0
Individual ID            0
Clutch Completion        0
Date Egg                 0
Culmen Length (mm)       2
Culmen Depth (mm)        2
Flipper Length (mm)      2
Body Mass (g)            2
Sex                     10
Delta 15 N (o/oo)       14
Delta 13 C (o/oo)       13
Comments               318
dtype: int64

In [132]:
df1.drop_duplicates(inplace=True)

In [133]:
df1.isna().sum()

studyName                0
Sample Number            0
Species                  0
Region                   0
Island                   0
Stage                    0
Individual ID            0
Clutch Completion        0
Date Egg                 0
Culmen Length (mm)       2
Culmen Depth (mm)        2
Flipper Length (mm)      2
Body Mass (g)            2
Sex                     10
Delta 15 N (o/oo)       14
Delta 13 C (o/oo)       13
Comments               318
dtype: int64

In [134]:
df1.columns

Index(['studyName', 'Sample Number', 'Species', 'Region', 'Island', 'Stage',
       'Individual ID', 'Clutch Completion', 'Date Egg', 'Culmen Length (mm)',
       'Culmen Depth (mm)', 'Flipper Length (mm)', 'Body Mass (g)', 'Sex',
       'Delta 15 N (o/oo)', 'Delta 13 C (o/oo)', 'Comments'],
      dtype='object')

In [135]:
df2=pd.DataFrame(df1,columns=['studyName', 'Sample Number', 'Region', 'Island', 'Stage',
       'Individual ID', 'Clutch Completion', 'Date Egg','Species'])
df2=df2.sample(200)

In [136]:
df2.sample(20)

,studyName,Sample Number,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Species
69,PAL0809,70,Anvers,Torgersen,"Adult, 1 Egg Stage",N32A2,No,11/11/08,Adelie Penguin (Pygoscelis adeliae)
68,PAL0809,69,Anvers,Torgersen,"Adult, 1 Egg Stage",N32A1,No,11/11/08,Adelie Penguin (Pygoscelis adeliae)
232,PAL0708,13,Anvers,Biscoe,"Adult, 1 Egg Stage",N37A1,Yes,11/29/07,Gentoo penguin (Pygoscelis papua)
204,PAL0910,53,Anvers,Dream,"Adult, 1 Egg Stage",N92A1,Yes,11/23/09,Chinstrap penguin (Pygoscelis antarctica)
313,PAL0910,94,Anvers,Biscoe,"Adult, 1 Egg Stage",N18A2,Yes,12/1/09,Gentoo penguin (Pygoscelis papua)
285,PAL0809,66,Anvers,Biscoe,"Adult, 1 Egg Stage",N20A2,Yes,11/4/08,Gentoo penguin (Pygoscelis papua)
175,PAL0708,24,Anvers,Dream,"Adult, 1 Egg Stage",N85A2,No,11/28/07,Chinstrap penguin (Pygoscelis antarctica)
298,PAL0809,79,Anvers,Biscoe,"Adult, 1 Egg Stage",N60A1,Yes,11/9/08,Gentoo penguin (Pygoscelis papua)
135,PAL0910,136,Anvers,Dream,"Adult, 1 Egg Stage",N77A2,Yes,11/13/09,Adelie Penguin (Pygoscelis adeliae)
39,PAL0708,40,Anvers,Dream,"Adult, 1 Egg Stage",N25A2,No,11/13/07,Adelie Penguin (Pygoscelis adeliae)
277,PAL0809,58,Anvers,Biscoe,"Adult, 1 Egg Stage",N16A2,Yes,11/3/08,Gentoo penguin (Pygoscelis papua)
130,PAL0910,131,Anvers,Torgersen,"Adult, 1 Egg Stage",N73A1,No,11/23/09,Adelie Penguin (Pygoscelis adeliae)
109,PAL0910,110,Anvers,Biscoe,"Adult, 1 Egg Stage",N55A2,Yes,11/20/09,Adelie Penguin (Pygoscelis adeliae)
90,PAL0809,91,Anvers,Dream,"Adult, 1 Egg Stage",N45A1,Yes,11/14/08,Adelie Penguin (Pygoscelis adeliae)
193,PAL0809,42,Anvers,Dream,"Adult, 1 Egg Stage",N74A2,Yes,11/24/08,Chinstrap penguin (Pygoscelis antarctica)
28,PAL0708,29,Anvers,Biscoe,"Adult, 1 Egg Stage",N18A1,No,11/10/07,Adelie Penguin (Pygoscelis adeliae)
73,PAL0809,74,Anvers,Torgersen,"Adult, 1 Egg Stage",N35A2,Yes,11/11/08,Adelie Penguin (Pygoscelis adeliae)
274,PAL0809,55,Anvers,Biscoe,"Adult, 1 Egg Stage",N15A1,Yes,11/4/08,Gentoo penguin (Pygoscelis papua)
4,PAL0708,5,Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,11/16/07,Adelie Penguin (Pygoscelis adeliae)
70,PAL0809,71,Anvers,Torgersen,"Adult, 1 Egg Stage",N34A1,Yes,11/14/08,Adelie Penguin (Pygoscelis adeliae)

In [137]:
df2['Species'].value_counts()

Species
Adelie Penguin (Pygoscelis adeliae)          94
Gentoo penguin (Pygoscelis papua)            73
Chinstrap penguin (Pygoscelis antarctica)    33
Name: count, dtype: int64

In [138]:
df2['studyName'].value_counts()

studyName
PAL0910    74
PAL0809    63
PAL0708    63
Name: count, dtype: int64

In [139]:
df2['studyName']=df2['studyName'].map({'PAL0708':0,'PAL0809':1,'PAL0910':2})

In [140]:
df2['Region']=df2['Region'].map({'Anvers':0})

In [141]:
df2.head()

,studyName,Sample Number,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Species
88,1,89,0,Dream,"Adult, 1 Egg Stage",N44A1,Yes,11/8/08,Adelie Penguin (Pygoscelis adeliae)
139,2,140,0,Dream,"Adult, 1 Egg Stage",N79A2,No,11/16/09,Adelie Penguin (Pygoscelis adeliae)
51,1,52,0,Biscoe,"Adult, 1 Egg Stage",N21A2,Yes,11/6/08,Adelie Penguin (Pygoscelis adeliae)
90,1,91,0,Dream,"Adult, 1 Egg Stage",N45A1,Yes,11/14/08,Adelie Penguin (Pygoscelis adeliae)
268,1,49,0,Biscoe,"Adult, 1 Egg Stage",N12A1,Yes,11/2/08,Gentoo penguin (Pygoscelis papua)

In [142]:
df2['Species_numeric']=df2['Species'].map({'Adelie Penguin (Pygoscelis adeliae)':0,'Gentoo penguin (Pygoscelis papua)':1,'Chinstrap penguin (Pygoscelis antarctica)':2})

In [143]:
df2.head(10)

,studyName,Sample Number,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Species,Species_numeric
88,1,89,0,Dream,"Adult, 1 Egg Stage",N44A1,Yes,11/8/08,Adelie Penguin (Pygoscelis adeliae),0
139,2,140,0,Dream,"Adult, 1 Egg Stage",N79A2,No,11/16/09,Adelie Penguin (Pygoscelis adeliae),0
51,1,52,0,Biscoe,"Adult, 1 Egg Stage",N21A2,Yes,11/6/08,Adelie Penguin (Pygoscelis adeliae),0
90,1,91,0,Dream,"Adult, 1 Egg Stage",N45A1,Yes,11/14/08,Adelie Penguin (Pygoscelis adeliae),0
268,1,49,0,Biscoe,"Adult, 1 Egg Stage",N12A1,Yes,11/2/08,Gentoo penguin (Pygoscelis papua),1
86,1,87,0,Dream,"Adult, 1 Egg Stage",N42A1,Yes,11/8/08,Adelie Penguin (Pygoscelis adeliae),0
180,1,29,0,Dream,"Adult, 1 Egg Stage",N62A1,Yes,11/14/08,Chinstrap penguin (Pygoscelis antarctica),2
3,0,4,0,Torgersen,"Adult, 1 Egg Stage",N2A2,Yes,11/16/07,Adelie Penguin (Pygoscelis adeliae),0
114,2,115,0,Biscoe,"Adult, 1 Egg Stage",N61A1,Yes,11/17/09,Adelie Penguin (Pygoscelis adeliae),0
326,2,107,0,Biscoe,"Adult, 1 Egg Stage",N28A1,Yes,11/10/09,Gentoo penguin (Pygoscelis papua),1

In [144]:
from sklearn.preprocessing import LabelEncoder

In [145]:
df2['Region'].value_counts()

Region
0    200
Name: count, dtype: int64

In [146]:
encoding=LabelEncoder()
encoding.fit_transform(df2['Region'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [147]:
df2

,studyName,Sample Number,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Species,Species_numeric
88,1,89,0,Dream,"Adult, 1 Egg Stage",N44A1,Yes,11/8/08,Adelie Penguin (Pygoscelis adeliae),0
139,2,140,0,Dream,"Adult, 1 Egg Stage",N79A2,No,11/16/09,Adelie Penguin (Pygoscelis adeliae),0
51,1,52,0,Biscoe,"Adult, 1 Egg Stage",N21A2,Yes,11/6/08,Adelie Penguin (Pygoscelis adeliae),0
90,1,91,0,Dream,"Adult, 1 Egg Stage",N45A1,Yes,11/14/08,Adelie Penguin (Pygoscelis adeliae),0
268,1,49,0,Biscoe,"Adult, 1 Egg Stage",N12A1,Yes,11/2/08,Gentoo penguin (Pygoscelis papua),1
...,...,...,...,...,...,...,...,...,...,...
218,2,67,0,Dream,"Adult, 1 Egg Stage",N100A1,Yes,11/21/09,Chinstrap penguin (Pygoscelis antarctica),2
24,0,25,0,Biscoe,"Adult, 1 Egg Stage",N13A1,Yes,11/10/07,Adelie Penguin (Pygoscelis adeliae),0
27,0,28,0,Biscoe,"Adult, 1 Egg Stage",N17A2,Yes,11/12/07,Adelie Penguin (Pygoscelis adeliae),0
28,0,29,0,Biscoe,"Adult, 1 Egg Stage",N18A1,No,11/10/07,Adelie Penguin (Pygoscelis adeliae),0
61,1,62,0,Biscoe,"Adult, 1 Egg Stage",N27A2,Yes,11/13/08,Adelie Penguin (Pygoscelis adeliae),0

In [148]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 88 to 61
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   studyName          200 non-null    int64
 1   Sample Number      200 non-null    int64
 2   Region             200 non-null    int64
 3   Island             200 non-null    object
 4   Stage              200 non-null    object
 5   Individual ID      200 non-null    object
 6   Clutch Completion  200 non-null    object
 7   Date Egg           200 non-null    object
 8   Species            200 non-null    object
 9   Species_numeric    200 non-null    int64
dtypes: int64(4), object(6)
memory usage: 17.2+ KB

In [149]:
df2.head(120)

,studyName,Sample Number,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Species,Species_numeric
88,1,89,0,Dream,"Adult, 1 Egg Stage",N44A1,Yes,11/8/08,Adelie Penguin (Pygoscelis adeliae),0
139,2,140,0,Dream,"Adult, 1 Egg Stage",N79A2,No,11/16/09,Adelie Penguin (Pygoscelis adeliae),0
51,1,52,0,Biscoe,"Adult, 1 Egg Stage",N21A2,Yes,11/6/08,Adelie Penguin (Pygoscelis adeliae),0
90,1,91,0,Dream,"Adult, 1 Egg Stage",N45A1,Yes,11/14/08,Adelie Penguin (Pygoscelis adeliae),0
268,1,49,0,Biscoe,"Adult, 1 Egg Stage",N12A1,Yes,11/2/08,Gentoo penguin (Pygoscelis papua),1
...,...,...,...,...,...,...,...,...,...,...
39,0,40,0,Dream,"Adult, 1 Egg Stage",N25A2,No,11/13/07,Adelie Penguin (Pygoscelis adeliae),0
230,0,11,0,Biscoe,"Adult, 1 Egg Stage",N36A1,No,11/27/07,Gentoo penguin (Pygoscelis papua),1
288,1,69,0,Biscoe,"Adult, 1 Egg Stage",N53A1,Yes,11/13/08,Gentoo penguin (Pygoscelis papua),1
173,0,22,0,Dream,"Adult, 1 Egg Stage",N73A2,Yes,12/3/07,Chinstrap penguin (Pygoscelis antarctica),2
243,0,24,0,Biscoe,"Adult, 1 Egg Stage",N42A2,Yes,11/27/07,Gentoo penguin (Pygoscelis papua),1

In [150]:
x=df2[['studyName','Sample Number','Region']]
y=df2['Species_numeric']

In [151]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,test_size=0.2,random_state=42)

In [152]:
NGassian=GaussianNB()
NGassian.fit(x_train,y_train)

GaussianNB()

In [157]:
NG_predict=NGassian.predict(x_test)
print(NG_predict)

[1 0 0 0 0 0 0 1 0 1 0 1 0 2 2 0 0 0 0 0 0 0 0 1 1 0 1 0 1 2 0 2 0 0 0 0 1
 0 0 2]

In [154]:
New_Samples=NGassian.predict([[1,1,3]])
print(New_Samples)

[0]

f:\ExternalSoftwares\Spyder\Vscode\python\packages\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

In [155]:
NG_Predict_pro=NGassian.predict_proba(x_test)
print(NG_Predict_pro)

[[3.15536433e-01 3.45976268e-01 3.38487299e-01]
 [7.32538061e-01 2.67404281e-01 5.76575387e-05]
 [3.97433190e-01 2.69348354e-01 3.33218456e-01]
 [3.84575840e-01 2.68522070e-01 3.46902090e-01]
 [4.71526539e-01 2.73626293e-01 2.54847168e-01]
 [3.47925247e-01 3.08501559e-01 3.43573194e-01]
 [4.76546582e-01 4.61069724e-01 6.23836946e-02]
 [3.24900670e-01 3.60559939e-01 3.14539392e-01]
 [3.97433190e-01 2.69348354e-01 3.33218456e-01]
 [4.54808514e-01 4.58289022e-01 8.69024641e-02]
 [6.88831339e-01 3.10948651e-01 2.20010015e-04]
 [4.01855963e-01 4.57926766e-01 1.40217271e-01]
 [8.05378087e-01 1.94617455e-01 4.45862423e-06]
 [3.47322246e-01 2.68621785e-01 3.84055969e-01]
 [3.54510010e-01 2.67942469e-01 3.77547521e-01]
 [7.44997535e-01 2.54963945e-01 3.85206867e-05]
 [7.20036455e-01 2.79878037e-01 8.55080118e-05]
 [4.19301268e-01 2.70876184e-01 3.09822548e-01]
 [3.70874608e-01 3.31447916e-01 2.97677476e-01]
 [8.38819775e-01 1.61179132e-01 1.09230327e-06]
 [7.32538061e-01 2.67404281e-01 5.76575387e-05]
 [4.27254065e-01 2.71410498e-01 3.01335437e-01]
 [3.78675696e-01 2.68202332e-01 3.53121971e-01]
 [3.99410665e-01 4.32452713e-01 1.68136622e-01]
 [3.19728865e-01 3.52990245e-01 3.27280890e-01]
 [5.09552744e-01 4.65892911e-01 2.45543457e-02]
 [3.74445012e-01 4.39024467e-01 1.86530521e-01]
 [4.44099734e-01 2.72432547e-01 2.83467719e-01]
 [3.17507433e-01 3.49409720e-01 3.33082847e-01]
 [3.32634211e-01 2.85003288e-01 3.82362501e-01]
 [6.46040106e-01 3.53208957e-01 7.50937840e-04]
 [3.32634211e-01 2.85003288e-01 3.82362501e-01]
 [4.92463635e-01 4.60109079e-01 4.74272867e-02]
 [5.13219557e-01 4.54960645e-01 3.18197988e-02]
 [7.38775353e-01 2.61177465e-01 4.71821232e-05]
 [7.93677999e-01 2.06315008e-01 6.99251863e-06]
 [3.48872114e-01 4.16417673e-01 2.34710212e-01]
 [4.04383532e-01 2.69831710e-01 3.25784758e-01]
 [5.14688962e-01 4.63364744e-01 2.19462940e-02]
 [3.45007019e-01 3.05059173e-01 3.49933808e-01]]

In [156]:
print(accuracy_score(y_test,NG_predict))

0.425