In [1]:
import numpy as  np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [2]:
df=pd.read_csv(r"lassoandridge.csv",encoding_errors='ignore')

In [4]:
df.shape

(30, 10)

In [5]:
df.ndim

2

In [6]:
df.size

300

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee ID          30 non-null     int64
 1   Age                  30 non-null     int64
 2   Department           30 non-null     object
 3   Salary               30 non-null     int64
 4   Years of Experience  30 non-null     int64
 5   Education Level      30 non-null     object
 6   Job Title            30 non-null     object
 7   Location             30 non-null     object
 8   Performance Rating   30 non-null     int64
 9   Years with Company   30 non-null     int64
dtypes: int64(6), object(4)
memory usage: 2.5+ KB

In [9]:
df.Department.value_counts()

Department
Sales         5
Marketing     5
IT            5
Finance       5
HR            5
Operations    5
Name: count, dtype: int64

In [10]:
df['new_dep']=df.Department.map({'Sales':0,'Marketing':1,'IT':2,'Finance':3,'HR':4,'Operations':5})

In [12]:
df.head(10)

,Employee ID,Age,Department,Salary,Years of Experience,Education Level,Job Title,Location,Performance Rating,Years with Company,new_dep
0,1,25,Sales,50000,2,Bachelor's,Sales Representative,New York,4,1,0
1,2,30,Marketing,60000,5,Master's,Marketing Manager,Chicago,5,3,1
2,3,28,IT,70000,3,Bachelor's,Software Engineer,San Francisco,4,2,2
3,4,35,Finance,80000,10,PhD,Financial Analyst,New York,5,5,3
4,5,22,HR,40000,1,Associate's,HR Representative,Los Angeles,3,1,4
5,6,40,Operations,90000,15,Bachelor's,Operations Manager,Chicago,5,10,5
6,7,29,Sales,55000,4,Bachelor's,Sales Representative,Houston,4,2,0
7,8,32,Marketing,65000,6,Master's,Marketing Manager,Seattle,5,4,1
8,9,26,IT,75000,4,Bachelor's,Software Engineer,Boston,4,3,2
9,10,38,Finance,85000,12,PhD,Financial Analyst,San Francisco,5,8,3

In [13]:
df['Education Level'].value_counts()

Education Level
Bachelor's     15
Master's        5
PhD             5
Associate's     5
Name: count, dtype: int64

In [14]:
df['new_edu']=df['Education Level'].map({"Associate's":0,"Bachelor's":1,"Master's":2,"PhD":3})

In [15]:
df.sample(2)

,Employee ID,Age,Department,Salary,Years of Experience,Education Level,Job Title,Location,Performance Rating,Years with Company,new_dep,new_edu
8,9,26,IT,75000,4,Bachelor's,Software Engineer,Boston,4,3,2,1
9,10,38,Finance,85000,12,PhD,Financial Analyst,San Francisco,5,8,3,3

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee ID          30 non-null     int64
 1   Age                  30 non-null     int64
 2   Department           30 non-null     object
 3   Salary               30 non-null     int64
 4   Years of Experience  30 non-null     int64
 5   Education Level      30 non-null     object
 6   Job Title            30 non-null     object
 7   Location             30 non-null     object
 8   Performance Rating   30 non-null     int64
 9   Years with Company   30 non-null     int64
 10  new_dep              30 non-null     int64
 11  new_edu              30 non-null     int64
dtypes: int64(8), object(4)
memory usage: 2.9+ KB

In [17]:
df.columns

Index(['Employee ID', 'Age', 'Department', 'Salary', 'Years of Experience',
       'Education Level', 'Job Title', 'Location', 'Performance Rating',
       'Years with Company', 'new_dep', 'new_edu'],
      dtype='object')

In [18]:
df1=pd.DataFrame(df,columns=['Age','new_dep','new_edu','Years with Company','Performance Rating','Salary'])

In [19]:
df1.sample(10)

    Age  new_dep  new_edu  Years with Company  Performance Rating  Salary
4    22        4        0                   1                   3   40000
24   33        0        1                   5                   4   62000
2    28        2        1                   2                   4   70000
21   41        3        3                  12                   5   92000
26   29        2        1                   6                   4   76000
1    30        1        2                   3                   5   60000
16   23        4        0                   1                   3   42000
6    29        0        1                   2                   4   55000
9    38        3        3                   8                   5   85000
22   28        4        0                   2                   3   48000

In [28]:
x=df1.iloc[1:,:-1]
y=df1.iloc[1:,-1]
y

1      60000
2      70000
3      80000
4      40000
5      90000
6      55000
7      65000
8      75000
9      85000
10     45000
11     95000
12     58000
13     68000
14     78000
15     88000
16     42000
17     98000
18     60000
19     72000
20     72000
21     92000
22     48000
23    100000
24     62000
25     74000
26     76000
27     94000
28     44000
29    102000
Name: Salary, dtype: int64

####https://www.youtube.com/watch?v=0yI0-r3Ly40

In [29]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split,cross_val_score

In [40]:
linear1=LinearRegression()
crs1=cross_val_score(linear1,x,y,scoring='neg_mean_squared_error',cv=4)
# mse_error=np.mean(crs1)
# print(mse_error)
print(crs1)

[-77595450.20315559 -44896946.12816767 -25173211.57766326
 -59852665.55243631]

In [20]:
df1['Salary'].max()

np.int64(102000)

In [22]:
df1['Salary'].mode()

0    60000
1    72000
Name: Salary, dtype: int64

In [23]:
df1['Salary'].median()

np.float64(72000.0)

In [24]:
df1['Salary'].sum()

np.int64(2138000)

In [21]:
df1['Salary'].min()

np.int64(40000)